### ISSUE TITLE
Chart Generation

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore#785]
Support the generation of charts by Query Builder. 
The chart configuration can be downloaded and saved on GeoStore for sharing. The charts data are generated by a WPS. 
- [x] Introduce support for chart libs (#787) 
- [x] Create chart options panel (#786)
- [x] Generate a chart from the data received from the WPS (#790)
- [x] Display data from WPS in a table (#791)
- [x] Export data in CSV (#792)
- [x] Export chart as png (#793)
- [x] Reporting panel with charts generated or imported during the session (#788)
- [x] Reload chart options from the report panel item (#789)
- [x] Reload fiter from the report panel item (#789)
- [x] **OPT** Cross-layer filtering
- [x] Save option
- [x] Download / Upload chart options from/to a file  ( #794)
- [x] Share / Load chart on GeoStore (by Id) (#795)
- [x] **OPT** show public charts avaliable on GeoStore. 
- [ ] cherry picks from c040. 

![wireframe-reporting-v3](https://cloud.githubusercontent.com/assets/1279510/12715685/f2c57a8c-c8db-11e5-8225-7412e236808b.png)

**Comment by offtherailz** [comment]
We will not port. closing
